### ISSUE TITLE
What's the license for these samples?

### ISSUE THREAD

**Issue by Jaxelr** [shawnwildermuth/codingshorts#1]
Shawn,

Thank you for all the time you invest in educating us. I was wondering what's the license on these samples?

Thanks,

**Comment by shawnwildermuth** [comment]
I haven't considered needing a license for these small demos, but I guess it's time to license them. Let me see which one I'll use, but it will be very permissive.

**Comment by shawnwildermuth** [comment]
Went with the Unlicense.
